yeatmanlab/roar-firekit

- jestconfig.json
- src/firestore/user.ts
> Allow additional user metadata

- src/firestore/firekit.ts
The PR creates the createUser function for firekit.
> Create user function

- firebase/admin/firestore.rules
- src/firestore/firekit.ts
- src/firestore/util.ts
This PR fixes OIDC integration for Clever auth by authenticating into the assessment project using the idToken from the admin firebase project.
> Fix clever OIDC

- src/firestore/app/run.ts
- src/firestore/firekit.ts
Also Do not update scores if assessment_stage does not equal either test_response or practice_response
> Require only one callback for computed/normed scores.

- src/firestore/firekit.ts
This PR adds support for all optional fields in mass uploader. In the near future, I would like to make this more dynamic rather than hardcoding each value. However I will wait for after the crunch to implement that, to leave time for ample testing. This way we have fine-grain control over the final location of each bit of data.
> Add support for all optional fields

- src/firestore/firekit.ts
Check if all **other** tasks have been completed before declaring assignment is completed.
> Fix assignment completion

- src/auth.ts
- src/firestore/firekit.ts
- src/firestore/interfaces.ts
This PR enables creation of admin user accounts and authentication of those user accounts using email link login.
> Add admin user

- firebase/admin/firestore.rules
- src/firestore/firekit.ts
Adds functions to allow users to get consent form documents and also write to their own consent object in the userdoc.
> Consent functions

- src/firestore/firekit.ts
and call it when an assessment starts and completes.
> Expose selectBestRun method

- src/firestore/firekit.ts
- src/firestore/query-admin.ts
And also remove the username check from createStudentWithUsernamePassword
> Add back the email availability function

- src/firestore/firekit.ts
Adds administrationId to the payload returning administration information
> Add id to administration info payload

- src/firestore/query-admin.ts
Quick fix regarding updates to the scores promise structure
> Remove flatten from scores promises

- src/firestore/query-admin.ts
This PR excludes runs that don't have a corresponding /runs/ entry. This allows the scores page to not hand indefinitely in the case of a messed up run. (This should be a rare occurrence anyway).
> Ignore runs that do not have a doc

- package-lock.json
- package.json
- src/firestore/firekit.ts
- src/firestore/interfaces.ts
This PR adds a function to Firekit that implements the createnewfamily function. This is simply a middle step where we format data on it's way to the cloud function for document creation.
> Create New Family

- package-lock.json
- package.json
- src/firestore/firekit.ts
Review with the following PRs
- [Cloud Functions](https://github.com/yeatmanlab/roar-firebase-functions/pull/225)
- [Dashboard](https://github.com/yeatmanlab/roar-dashboard/pull/490)
> Add ClassLink auth provider

- src/firestore/firekit.ts
Also exports restConfig as a function rather than a getter
Also also adds minor verboseLogging to getMyData functions
> Force Token Refresh

- src/firestore/firekit.ts
This PR adds functionality for updating tasks and variants as a Firekit method.
> Update Tasks and Variants Firekit Method

- src/firestore/firekit.ts
Adding the orgCode to the child if given
> Activation code for child data

- src/firestore/firekit.ts
Adding activation code to student data
> adding activationCode to student data

- src/firestore/app/appkit.ts
- src/firestore/app/run.ts
This change allows meta data to be written when the task is complete, such as the reason the task ended. For example, they reached the time limit, they reached the maximum allowed incorrect responses, an error, etc.
> Allowing run to store additional meta data on finish

- src/firestore/firekit.ts
This PR sets admin checks to true if the admin property is on the userClaims doc.
> Adding admin check for levante

- src/firestore/app/appkit.ts
- src/firestore/app/run.ts
- src/firestore/firekit.ts
This PR extends the enhancement from PR #123 to all Firebase projects.
> ENH: Allow all projects to write finishing metadata

- src/firestore/firekit.ts
Adds a function to update user  data for a specific user. It is my belief we should use firekit functions for most instances of non-lab admins editing database items, as it gives us control over the data edited and permissions of those who attempt to do so.
> Edit Users Function

- package.json
- src/firestore/firekit.ts
- src/firestore/interfaces.ts
Adds a function to update a user's record, include it as part of the updateUserData function to update passwords
> Update User Record

- src/firekit.ts
- **adding createAdobeSignAgreement function**
- **adding adobeSign cloud functions**
> AdobeSign Integration

- src/auth.ts
- src/firekit.ts
- Allows password as an option to unlink from user profile
- Make a more complete list of auth login methods from fetch function
> Utils for Admin Profile 

- src/firekit.ts
> Add getTasksDictionary fx

- .gitignore
- package-lock.json
- src/firekit.ts
- src/firestore/util.ts
- tsconfig.json
Companion PR: https://github.com/yeatmanlab/roar-dashboard/pull/743
This PR sets up Firebase App Check for use within Firekite and the Dashboard. App Check uses reCAPTCHA tokens to verify that all requests are coming from a list of allowed domains.
> Add Firebase App Check

- src/firestore/util.ts
> fix/App Check

- src/firekit.ts
- src/firestore/util.ts
This is a companion PR to https://github.com/yeatmanlab/roar-firebase-functions/pull/264. It removes clever from the list of providers that call `_syncEduSSOUser` every time someone logs in. Because of the changes in the roar-firebase-functions PR mentioned above, Clever users are now pre-allocated, eliminating the need to import their information every time they log in.
As a result of the changes in the roar-firebase-functions PR, we also have to change the call signature for the set-uid-claims handler. It now accepts optional parameters for the identity provider type and identity provider ID.
> Remove clever from edu-sso-sync and add identity provider info to set uid claims call

- src/firekit.ts
Modify Firekit to always set a key for testData in admin docs; defaults to false.
> fix/Flag Test Data

- src/firekit.ts
User linking handler function. Moving LEVANTE functions together. 
> adding User linking handler

- src/firekit.ts
> Update assessment related functions to use roarUid rather than adminUid

- src/firekit.ts
This PR fixes a bug in which the roarUid would point to the adminUid. Now it points to a private `_roarUid` string that is updated on an auth state change and also updated whenever the `getRoarUid()` method is called.
> Make this.roarUid actually reference the roarUid

- src/firestore/app/run.ts
Co-authored-by: kellyel <kellyel@users.noreply.github.com>
We’ve added a control to ensure that not only the keys are present but also that their values are not undefined before moving forward.
> Fix: games requiredKeys values not undefined

- src/firekit.ts
This PR adds a method to call a cloud function that retrieves a list of administration IDs. It is intended to be called by administrators. The motivation for this change is that we are refactoring the way that administrations are queried and indexed and users will no longer be able to query by `readOrgs` in the administration document.
> Add method to get administration IDs for an administrator

- src/firekit.ts
- src/interfaces.ts
This PR will change the way we grab variant params before starting an assessment. Previously, we grabbed the administration document to gather the params for the given task. With this change, we will be grabbing params directly from the assignment document at `/users/{userId}/assignments/{assignmentId}`. This will remove the need for users to have access to the administrations collection, and lessen the client's calls by one. 
> [!CAUTION]  
> This should not be merged until we have denormalized the task params over to the assignment doc. If merged before, we will no longer be able to launch the tasks correctly. 
> Grab variant params from assignment doc rather than administration doc

- src/firekit.ts
This PR adds `archived: false` to all new orgs created by the `createOrg` firekit method.
> Add archived: false to new orgs

- src/firestore/util.ts
This PR comments out anything related to Firebase AppCheck
> Remove Firebase App Check

- src/firekit.ts
Co-authored-by: Adam Richie-Halford <richford@users.noreply.github.com>
> Delete Admin Subcollections

- src/firekit.ts
> Update assessment methods to allow for targetUid passthrough

- src/constants/permissions.ts
- src/services/permissions.service.test.ts
- src/services/permissions.service.ts
- src/utils/flattenObjectValues.util.ts
This PR introduces additional functionality to the permissions service. The permissions service will now verify that a permission is valid rather than just returning false for undefined permissions. This is an additional safeguard against non-existing permissions being added to code. If a permission is not valid, it will error rather than returning false. This can serve as an early warning to developers adding permissions to other repos. 
> Permission Validation

- src/constants/permissions.ts
- src/constants/roles.ts
- src/constants/user-roles.ts
This pull request adds the launch_admin role and the `Permissions.task.LAUNCH` permission. 
> Add launch_admin role

- src/firestore/app/run.ts
**Write browser interaction**
Writes all interaction events in run doc (blur, focus, and fullscreen)
> Write app interaction data to run docs

- .github/workflows/ci.yml
- src/firestore/app/appkit.ts
- src/firestore/app/run.ts
This PR enhances the interaction logging system by:
- Saving timestamps for each event, including _blur, focus, fullscreenenter,_ and _fullscreenexit_.
- If we don't specify then record all 4 interactions, otherwise record the specified ones. 
- Categorizing interaction events by `assessment_stage`, grouped into practice, test, or break levels for the run data.
- Tracking each event only once per trial per stage to avoid duplicate counts.
- Safely updating the `interactions` in Firestore using `increment()`, **with no read access required**.
Example of result on run level data:
Example of result on trial level data:
> Interaction Data Runs Summary

- src/firekit.ts
- src/interfaces.ts
This PR fixes a potential issue that @maximilianoertel identified where the restConfig can be malformed. Currently, if the `restConfig` is requested before the `_idTokens` are available, firekit will still return a header object with `Bearer undefined`. With these changes, it returns `undefined` if the idTokens are undefined.
> Return undefined for restConfig if the idTokens are not available.

- src/firekit.ts
- src/interfaces.ts
This PR transforms the restConfig getter with a method. Updating to a method allows us to specify whether the user intends to use the config for an unauthenticated function, and if so returning the baseUrl (and headers only if they exist). This is helpful for situations like the parent sign-up, where we need to access an 'allow unauthenticated' cloud function before the user is logged in. 
> Allow grabbing restConfig without having idTokens when requested

- src/constants/permissions.ts
This PR adds a permission to allow users to see the composite scores on the score report.
> Add permission for viewing composite scores

- src/firekit.ts
Adds verifyParentRegistration to allow invocation of cloud function. 
> add verifyParentRegistration Method

- LICENSE
- package-lock.json
- package.json
This PR switches roar-firekit back to the ISC License. This will allow wider adoption (e.g., by LEVANTE)
> Switch back to ISC License

- .github/workflows/publish.yml
This PR verifies whether newly pushed tag refers to a commit on the main branch. Otherwise, it exits the workflow.
These changes were tested on mock branch temp/update-publish-config-test using tag dry-test-run:
Test branch: https://github.com/yeatmanlab/roar-firekit/tree/temp/update-publish-config-test
Success (commit exists on the mock branch): https://github.com/yeatmanlab/roar-firekit/actions/runs/15830765086/job/44622603028
Fail (mock commit does not exist on main): https://github.com/yeatmanlab/roar-firekit/actions/runs/15830444029/job/44621528041
Tests were done with a mock branch. 
Resolves https://github.com/yeatmanlab/roar-project-management/issues/793
> Update publish workflow with tag validation 

- src/firekit.ts
This PR adds a function to firekit. This function calls the cloud function to retrieve all taskBundles from the database.
> [ENH] Query for task bundles

- .github/workflows/publish.yml
Do not fetch tags in publish.yml.
> Do not fetch tags in publish.yml

- package.json
> Update repository and version number

- src/firekit.ts
This PR adds the NYCPS SSO provider. It is a prerequisite PR for https://github.com/yeatmanlab/roar-dashboard/pull/1319
WIP
> Add NYCPS SSO Provider
